'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TWG.PdfByTitle.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property IndexValueButtonImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IndexValueButtonImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Access Databases.
        '''</summary>
        Friend ReadOnly Property strAccessDatabases() As String
            Get
                Return ResourceManager.GetString("strAccessDatabases", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Access (.mdb) &amp;file name:.
        '''</summary>
        Friend ReadOnly Property strAccessDb() As String
            Get
                Return ResourceManager.GetString("strAccessDb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All Files.
        '''</summary>
        Friend ReadOnly Property strAllFiles() As String
            Get
                Return ResourceManager.GetString("strAllFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to and More.
        '''</summary>
        Friend ReadOnly Property strAndMore() As String
            Get
                Return ResourceManager.GetString("strAndMore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}
        '''The directory does not exist. Create it?.
        '''</summary>
        Friend ReadOnly Property strAskToCreateDir() As String
            Get
                Return ResourceManager.GetString("strAskToCreateDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Access database file name is either missing or invalid.  Please check this value and try again..
        '''</summary>
        Friend ReadOnly Property strBadAccessName() As String
            Get
                Return ResourceManager.GetString("strBadAccessName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The connection string value is either missing or invalid.  Please check this value and try again..
        '''</summary>
        Friend ReadOnly Property strBadConnectionString() As String
            Get
                Return ResourceManager.GetString("strBadConnectionString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bad database type selection..
        '''</summary>
        Friend ReadOnly Property strBadDbType() As String
            Get
                Return ResourceManager.GetString("strBadDbType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name must be 32 characters or less..
        '''</summary>
        Friend ReadOnly Property strBadDestination() As String
            Get
                Return ResourceManager.GetString("strBadDestination", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The drive letter is missing or bad..
        '''</summary>
        Friend ReadOnly Property strBadDriveLetter() As String
            Get
                Return ResourceManager.GetString("strBadDriveLetter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An invalid directory was specified for Image Files..
        '''</summary>
        Friend ReadOnly Property strBadImageDirectory() As String
            Get
                Return ResourceManager.GetString("strBadImageDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An invalid directory was specified for Kofax PDF Files..
        '''</summary>
        Friend ReadOnly Property strBadKfxPdfDirectory() As String
            Get
                Return ResourceManager.GetString("strBadKfxPdfDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An invalid directory was specified for OCR Full Text Files..
        '''</summary>
        Friend ReadOnly Property strBadOcrDirectory() As String
            Get
                Return ResourceManager.GetString("strBadOcrDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The workgroup file name is invalid.  Please check this value and try again..
        '''</summary>
        Friend ReadOnly Property strBadWorkgroupName() As String
            Get
                Return ResourceManager.GetString("strBadWorkgroupName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Batch class:.
        '''</summary>
        Friend ReadOnly Property strBatchClass() As String
            Get
                Return ResourceManager.GetString("strBatchClass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changing this value will break all of the currently defined links.  Continue?.
        '''</summary>
        Friend ReadOnly Property strBreakAllDbLinks() As String
            Get
                Return ResourceManager.GetString("strBreakAllDbLinks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changing the Documents table will break the current Document ID and Document Path links.  Continue?.
        '''</summary>
        Friend ReadOnly Property strBreakDocIdPath() As String
            Get
                Return ResourceManager.GetString("strBreakDocIdPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changing this table will cause all of the index links to be broken.  Continue?.
        '''</summary>
        Friend ReadOnly Property strBreakIndexLinks() As String
            Get
                Return ResourceManager.GetString("strBreakIndexLinks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database Columns.
        '''</summary>
        Friend ReadOnly Property strDatabaseColumns() As String
            Get
                Return ResourceManager.GetString("strDatabaseColumns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Verification.
        '''</summary>
        Friend ReadOnly Property strDataVerify() As String
            Get
                Return ResourceManager.GetString("strDataVerify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Verification Failed.
        '''</summary>
        Friend ReadOnly Property strDataVerifyFail() As String
            Get
                Return ResourceManager.GetString("strDataVerifyFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database Connection Failure.
        '''</summary>
        Friend ReadOnly Property strDbConnectionFailed() As String
            Get
                Return ResourceManager.GetString("strDbConnectionFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This document was already exported.
        '''</summary>
        Friend ReadOnly Property strDocAlreadyReleased() As String
            Get
                Return ResourceManager.GetString("strDocAlreadyReleased", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Document class:.
        '''</summary>
        Friend ReadOnly Property strDocClass() As String
            Get
                Return ResourceManager.GetString("strDocClass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Document Table column.
        '''</summary>
        Friend ReadOnly Property strDocColumnError() As String
            Get
                Return ResourceManager.GetString("strDocColumnError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This column is missing in the Documents table of your database.
        '''</summary>
        Friend ReadOnly Property strDocColumnMissing() As String
            Get
                Return ResourceManager.GetString("strDocColumnMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Document Table.
        '''</summary>
        Friend ReadOnly Property strDocTableError() As String
            Get
                Return ResourceManager.GetString("strDocTableError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Document ID.
        '''</summary>
        Friend ReadOnly Property strDocumentId() As String
            Get
                Return ResourceManager.GetString("strDocumentId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data &amp;source name:.
        '''</summary>
        Friend ReadOnly Property strDsn() As String
            Get
                Return ResourceManager.GetString("strDsn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Index Table column.
        '''</summary>
        Friend ReadOnly Property strIndexColumnError() As String
            Get
                Return ResourceManager.GetString("strIndexColumnError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This column is missing in the Index table of your database.
        '''</summary>
        Friend ReadOnly Property strIndexColumnMissing() As String
            Get
                Return ResourceManager.GetString("strIndexColumnMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Index is same as document..
        '''</summary>
        Friend ReadOnly Property strIndexSameAsDoc() As String
            Get
                Return ResourceManager.GetString("strIndexSameAsDoc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Index Value.
        '''</summary>
        Friend ReadOnly Property strIndexValue() As String
            Get
                Return ResourceManager.GetString("strIndexValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must have a link to all required database fields..
        '''</summary>
        Friend ReadOnly Property strLinkToRequiredFieldMissing() As String
            Get
                Return ResourceManager.GetString("strLinkToRequiredFieldMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The required link to the Document ID is missing.
        '''</summary>
        Friend ReadOnly Property strMissingDocIdLink() As String
            Get
                Return ResourceManager.GetString("strMissingDocIdLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missing image type:.
        '''</summary>
        Friend ReadOnly Property strMissingImageType() As String
            Get
                Return ResourceManager.GetString("strMissingImageType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Name:.
        '''</summary>
        Friend ReadOnly Property strName() As String
            Get
                Return ResourceManager.GetString("strName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Document ID link has been selected..
        '''</summary>
        Friend ReadOnly Property strNoDocIdLink() As String
            Get
                Return ResourceManager.GetString("strNoDocIdLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Document path link has been selected..
        '''</summary>
        Friend ReadOnly Property strNoDocPathLink() As String
            Get
                Return ResourceManager.GetString("strNoDocPathLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Documents table was selected..
        '''</summary>
        Friend ReadOnly Property strNoDocTable() As String
            Get
                Return ResourceManager.GetString("strNoDocTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No directory was specified for Image Files..
        '''</summary>
        Friend ReadOnly Property strNoImageDirectory() As String
            Get
                Return ResourceManager.GetString("strNoImageDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An Index table was not selected..
        '''</summary>
        Friend ReadOnly Property strNoIndexTable() As String
            Get
                Return ResourceManager.GetString("strNoIndexTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Kofax PDF export directory cannot be blank. Please specify a valid path..
        '''</summary>
        Friend ReadOnly Property strNoKfxPdfDirectory() As String
            Get
                Return ResourceManager.GetString("strNoKfxPdfDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No directory was specified for OCR Full Text Files..
        '''</summary>
        Friend ReadOnly Property strNoOcrDirectory() As String
            Get
                Return ResourceManager.GetString("strNoOcrDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected table cannot be used as the Documents table..
        '''</summary>
        Friend ReadOnly Property strNotADocTable() As String
            Get
                Return ResourceManager.GetString("strNotADocTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The following Batch Fields were not used..
        '''</summary>
        Friend ReadOnly Property strNotAllBatchFieldsUsed() As String
            Get
                Return ResourceManager.GetString("strNotAllBatchFieldsUsed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The following Index Fields were not used..
        '''</summary>
        Friend ReadOnly Property strNotAllIndexFieldsUsed() As String
            Get
                Return ResourceManager.GetString("strNotAllIndexFieldsUsed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to connect to the database..
        '''</summary>
        Friend ReadOnly Property strNotConnectedToDb() As String
            Get
                Return ResourceManager.GetString("strNotConnectedToDb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected table contains no columns. Add columns to the table before proceeding..
        '''</summary>
        Friend ReadOnly Property strNotValidIndexTable() As String
            Get
                Return ResourceManager.GetString("strNotValidIndexTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You do not have the required permission for the selected table ‘{0}&apos;. Add the necessary permissions to the table before proceeding..
        '''</summary>
        Friend ReadOnly Property strNotValidTable() As String
            Get
                Return ResourceManager.GetString("strNotValidTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The table contains no columns that can be mapped to the Document ID.  The Document ID requires a column with datatype Integer (2 bytes) or Long Integer (4 bytes)..
        '''</summary>
        Friend ReadOnly Property strNoValidDocId() As String
            Get
                Return ResourceManager.GetString("strNoValidDocId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The table contains no columns that can be mapped to the Document Path.  The Document Path requires a column with datatype Char, Text, or Memo..
        '''</summary>
        Friend ReadOnly Property strNoValidDocPath() As String
            Get
                Return ResourceManager.GetString("strNoValidDocPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OCR Full Text Files will be discarded at export time..
        '''</summary>
        Friend ReadOnly Property strOcrFilesDiscarded() As String
            Get
                Return ResourceManager.GetString("strOcrFilesDiscarded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not allocate the ODBC environment..
        '''</summary>
        Friend ReadOnly Property strOdbcEnvironment() As String
            Get
                Return ResourceManager.GetString("strOdbcEnvironment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to build list of ODBC Data Sources..
        '''</summary>
        Friend ReadOnly Property strOdbcFailed() As String
            Get
                Return ResourceManager.GetString("strOdbcFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The PDF 2.01 image format is not supported.
        '''Please run export setup to choose a different image format..
        '''</summary>
        Friend ReadOnly Property strPdfPublishFailed() As String
            Get
                Return ResourceManager.GetString("strPdfPublishFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have previously selected PDF 2.01 image format which is no longer supported in this release of Kofax Capture.
        '''The image format will be set to Multipage TIFF - CCITT Group 4..
        '''</summary>
        Friend ReadOnly Property strPdfSetupFailed() As String
            Get
                Return ResourceManager.GetString("strPdfSetupFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Probably lacking unique index..
        '''</summary>
        Friend ReadOnly Property strReadOnlyError() As String
            Get
                Return ResourceManager.GetString("strReadOnlyError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Press OK to remove the associated link or Cancel to exit Export Setup..
        '''</summary>
        Friend ReadOnly Property strRemoveLinkOrQuit() As String
            Get
                Return ResourceManager.GetString("strRemoveLinkOrQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you wish to save the current settings?.
        '''</summary>
        Friend ReadOnly Property strSaveSettings() As String
            Get
                Return ResourceManager.GetString("strSaveSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Batch Fields.
        '''</summary>
        Friend ReadOnly Property strTextBatchFields() As String
            Get
                Return ResourceManager.GetString("strTextBatchFields", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text Constant.
        '''</summary>
        Friend ReadOnly Property strTextConst() As String
            Get
                Return ResourceManager.GetString("strTextConst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Document Index Fields.
        '''</summary>
        Friend ReadOnly Property strTextDocIndexField() As String
            Get
                Return ResourceManager.GetString("strTextDocIndexField", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Folder Index Fields.
        '''</summary>
        Friend ReadOnly Property strTextFolderIndexField() As String
            Get
                Return ResourceManager.GetString("strTextFolderIndexField", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kofax Capture Values.
        '''</summary>
        Friend ReadOnly Property strTextKCValues() As String
            Get
                Return ResourceManager.GetString("strTextKCValues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unlink Field.
        '''</summary>
        Friend ReadOnly Property strTextUnlinkField() As String
            Get
                Return ResourceManager.GetString("strTextUnlinkField", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database Export Setup.
        '''</summary>
        Friend ReadOnly Property strTitleDatabase() As String
            Get
                Return ResourceManager.GetString("strTitleDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drive/Directory Problem.
        '''</summary>
        Friend ReadOnly Property strTitleDirNotExist() As String
            Get
                Return ResourceManager.GetString("strTitleDirNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database Export Error.
        '''</summary>
        Friend ReadOnly Property strTitleReleaseError() As String
            Get
                Return ResourceManager.GetString("strTitleReleaseError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database Export Setup Error.
        '''</summary>
        Friend ReadOnly Property strTitleReleaseSetupError() As String
            Get
                Return ResourceManager.GetString("strTitleReleaseSetupError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Settings.
        '''</summary>
        Friend ReadOnly Property strTitleSaveSettings() As String
            Get
                Return ResourceManager.GetString("strTitleSaveSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Image Export Directory.
        '''</summary>
        Friend ReadOnly Property strTitleSelectImgDir() As String
            Get
                Return ResourceManager.GetString("strTitleSelectImgDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select OCR Export Directory.
        '''</summary>
        Friend ReadOnly Property strTitleSelectOcrDir() As String
            Get
                Return ResourceManager.GetString("strTitleSelectOcrDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Kofax PDF Export Directory.
        '''</summary>
        Friend ReadOnly Property strTitleSelectPdfDir() As String
            Get
                Return ResourceManager.GetString("strTitleSelectPdfDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The current settings are unusable.  Do you want to use the default settings?.
        '''</summary>
        Friend ReadOnly Property strUseDefault() As String
            Get
                Return ResourceManager.GetString("strUseDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Workgroup Files.
        '''</summary>
        Friend ReadOnly Property strWorkgroupFiles() As String
            Get
                Return ResourceManager.GetString("strWorkgroupFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to True.
        '''</summary>
        Friend ReadOnly Property TXT_LocalizedValueTrue() As String
            Get
                Return ResourceManager.GetString("TXT_LocalizedValueTrue", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
